language: ruby
rvm:
  - 2.4.1

before_install:
  - openssl aes-256-cbc -K $encrypted_515c9a6f15a6_key -iv $encrypted_515c9a6f15a6_iv -in s3cfg-prod.enc -out s3cfg-prod -d
  - gem update --system
  - gem install bundler

script: bundle exec jekyll build --future --config _config.yml,_config_build.yml

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

before_deploy: 
  - pip install --user s3cmd
  - pip install --user awscli

deploy:
    provider: script
    script: ~/.local/bin/s3cmd sync --config s3cfg-prod --guess-mime-type --no-mime-magic --delete-removed --exclude '.sass-cache' --exclude 's3cfg*' _site/ s3://www.fullofwishes.co.uk/database/
    skip_cleanup: true 
notifications:
    email:
        on_failure: always
after_deploy:
    aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/database/*"
