# Site settings
title: 'A Head Full of Wishes'
subtitle: 'Releases, shows and tracks'
email: andy@fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://db.fullofwishes.co.uk" # the base hostname & protocol for your site
image: http://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
twitter_username: ahfow
github_username:  grange85

collections: 
  releases:
    output: true
  tracks:
    output: true
    permalink: tracks/:title.html
  galaxie-500-shows:
    output: true
    permalink: galaxie-500/shows/:title.html
  luna-shows:
    output: true
    permalink: luna/shows/:title.html
  damon-and-naomi-shows:
    output: true
    permalink: damon-and-naomi/shows/:title.html
  dean-and-britta-shows:
    output: true
    permalink: dean-and-britta/shows/:title.html
  dean-wareham-shows:
    output: true
    permalink: dean-wareham/shows/:title.html


defaults: 
  -
    scope:
      path: ""
      type: galaxie-500-shows
    values:
      artistslug: galaxie-500
  -
    scope:
      path: ""
      type: luna-shows
    values:
      artistslug: luna
  -
    scope:
      path: ""
      type: damon-and-naomi-shows
    values:
      artistslug: damon-and-naomi
  -
    scope:
      path: ""
      type: dean-and-britta-shows
    values:
      artistslug: dean-and-britta
  -
    scope:
      path: ""
      type: dean-wareham-shows
    values:
      artistslug: dean-wareham


# Build settings
markdown: kramdown
source: /Volumes/XANDER3/06-AHFOW_JEKYLL/
destination: /Volumes/XANDER3/db.fullofwishes.co.uk/
exclude: [
    '_notes'
#    '_galaxie-500-shows',
#    '_luna-shows',
#    '_damon-and-naomi-shows',
#    '_dean-and-britta-shows',
#    '_dean-wareham-shows',
#    '_tracks',
#    'tracks'
  ]
gems: [
        jekyll-sitemap,
        jekyll-last-modified-at
      ]
