# Site settings
title: 'A Head Full of Wishes: data'
email: andy@fullofwishes.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A Head Full of Wishes is a fan site for Galaxie 500, Luna, Damon and Naomi, Dean and Britta and Dean Wareham,
  it includes news as well as an extensive discography and gigography
baseurl: "/database" # the subpath of your site, e.g. /blog/
url: "http://static.fullofwishes.co.uk" # the base hostname & protocol for your site
twitter_username: ahfow
github_username:  grange85
ahfow_artists: 
  - artist: Galaxie 500
    artistslug: galaxie-500
  - artist: Luna
    artistslug: Luna
  - artist: Damon and Naomi
    artistslug: damon-and-naomi
  - artist: Dean and Britta
    artistslug: dean-and-britta
  - artist: Dean Wareham
    artistslug: dean-wareham

releases_categories: [
  '01-album',
  '02-single',
  '03-compilation',
  '04-promo',
  '05-video'
  ]

collections: 
  releases:
    output: true
  tracks:
    output: true
    permalink: tracks/:title.html
  galaxie-500-shows:
    output: true
    permalink: galaxie-500/shows/:title.html

# Build settings
markdown: kramdown
exclude: [
  'tracks-exclude',
  'luna/shows',
  'damon-and-naomi/shows',
  'dean-and-britta/shows',
  'dean-wareham/shows'
  ]
gems: 
   - jekyll-sitemap
