# Site settings
title: 'A Head Full of Wishes: Discography / Gigography'
subtitle: 'Discography / Gigography'
author: Andy Aldridge
og_image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image-1280x720.jpg
email: andy@fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
baseurl: "/database" # the subpath of your site, e.g. /blog/
url: "https://www.fullofwishes.co.uk" # the base hostname and protocol for your site
banner_image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image-1280x200.jpg
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image-1280x720.jpg
twitter_username: ahfow
github_username:  grange85
theme: no-style-please
favicon: "favicon-32x32.png"
defaults:
  - scope:
      path: ""
    values:
      image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image-1280x720.jpg
    
theme_config:
  appearance: "dark"
  back_home_text: "<-- back to database home"
  main_site_back_text: "<-- A Head Full of Wishes home"
  date_format: "%Y-%m-%d"
  show_description: true
plausible_domain: fullofwishes.co.uk
goat_counter: fullofwishes
collections_dir: collections
collections:
  galaxie-500-releases:
    output: true
    permalink: galaxie-500/releases/:title/
  luna-releases:
    output: true
    permalink: luna/releases/:title/
  damon-and-naomi-releases:
    output: true
    permalink: damon-and-naomi/releases/:title/
  dean-and-britta-releases:
    output: true
    permalink: dean-and-britta/releases/:title/
  dean-wareham-releases:
    output: true
    permalink: dean-wareham/releases/:title/

page_gen-dirs: true
page_gen:
- data: shows
  template: show
  dir_expr: record['artistslug'].to_s + "/shows/" + Date.parse(record['date']).strftime("%Y")
  index_files: true
  name_expr:  record['slug'].to_s
  title_expr: record['artistname'].to_s + " / " + Date.parse(record['date']).strftime("%-d %B %Y") + " - " + record['venue'].to_s 
  page_data_prefix: ahfow 
- data: songs
  template: track
  dir: tracks
  index_files: true
  name_expr: record['slug']
  title_expr: record['title']
  page_data_prefix: ahfow

sqlite:
  - data: shows
    file: &db "_db/music.db"
    query: SELECT s.id as id, v.name as name, v.city as city, concat(a.slug, '/shows/', s.slug) as generated_path, v.state as state, v.country as venue, a.name as artistname, a.slug as artistslug, s.date as date, s.performers as performers, s.slug as slug from venues v, acts a, shows s WHERE v.id = s.venue_id
  - data: songs
    file: *db
    query: SELECT * from songs ORDER BY sort_title
  - data: acts
    file: *db
    query: SELECT * from acts

# Build settings
future: true
livereload: false
host: 0.0.0.0
port: 4000
environment: development
markdown: kramdown
kramdown:
    smart_quotes:  ["lsquo", "rsquo", "ldquo", "rdquo"]
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'vendor',
    's3cfg-prog',
    's3cfg-prog.enc',
    'vendor',
    'deploy.sh',
    '_deploy'
  ]
plugins:
 - jekyll-datapage-generator
 - jekyll-feed
 - jekyll_sqlite

