# Site settings
title: 'A Head Full of Wishes: data'
email: andy@fullofwishes.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A Head Full of Wishes is a fan site for Galaxie 500, Luna, Damon and Naomi, Dean and Britta and Dean Wareham,
  it includes news as well as an extensive discography and gigography
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://db.fullofwishes.co.uk" # the base hostname & protocol for your site
twitter_username: ahfow
github_username:  grange85
ahfow_artists: 
  - artist: Galaxie 500
    artistslug: galaxie-500
  - artist: Luna
    artistslug: luna
  - artist: Damon and Naomi
    artistslug: damon-and-naomi
  - artist: Dean and Britta
    artistslug: dean-and-britta
  - artist: Dean Wareham
    artistslug: dean-wareham

collections: 
  releases:
    output: true
  tracks:
    output: true
    permalink: tracks/:title.html
  galaxie-500-shows:
    output: true
    permalink: galaxie-500/shows/:title.html
  luna-shows:
    output: true
    permalink: luna/shows/:category/:title.html
  damon-and-naomi-shows:
    output: true
    permalink: damon-and-naomi/shows/:title.html
  dean-and-britta-shows:
    output: true
    permalink: dean-and-britta/shows/:title.html
  dean-wareham-shows:
    output: true
    permalink: dean-wareham/shows/:title.html

# Build settings
markdown: kramdown
exclude: [
#    '_galaxie-500-shows',
#    '_luna-shows',
#    '_damon-and-naomi-shows',
#    '_dean-and-britta-shows',
#    '_dean-wareham-shows',
#    '_tracks',
#    'tracks'
  ]
gems: 
   - jekyll-sitemap
