# Site settings
title: 'A Head Full of Wishes'
subtitle: 'Discography / Gigography'
email: andy@fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
baseurl: "/database" # the subpath of your site, e.g. /blog/
url: "https://www.fullofwishes.co.uk" # the base hostname and protocol for your site
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
twitter_username: ahfow
github_username:  grange85

sass:
  sass_dir: _sass

collections_dir: collections
collections:
  tracks:
    output: true
    permalink: tracks/:title/
  galaxie-500-releases:
    output: true
    permalink: galaxie-500/releases/:title/
  luna-releases:
    output: true
    permalink: luna/releases/:title/
  damon-and-naomi-releases:
    output: true
    permalink: damon-and-naomi/releases/:title/
  dean-and-britta-releases:
    output: true
    permalink: dean-and-britta/releases/:title/
  dean-wareham-releases:
    output: true
    permalink: dean-wareham/releases/:title/


page_gen-dirs: true
page_gen:
- data: discography.dean-and-britta-shows
  template: show
  dir: dean-and-britta/shows
  index_files: true
  name_expr: record['slug'] + "-" + Date.parse(record['date']).strftime('%Y-%m-%d') + record['disambiguate'].to_s + '-' + record['venue-slug']
  title_expr: record['artistname'] + " / " + Date.parse(record['date']).strftime("%-d %B %Y") + " - " + record['venue']
  page_data_prefix: ahfow 
- data: discography.luna-shows
  template: show
  dir: luna/shows
  index_files: true
  name_expr: record['slug'] + "-" + Date.parse(record['date']).strftime('%Y-%m-%d') + record['disambiguate'].to_s + '-' + record['venue-slug']
  title_expr: record['artistname'] + " / " + Date.parse(record['date']).strftime("%-d %B %Y") + " - " + record['venue']
  page_data_prefix: ahfow 
- data: discography.galaxie-500-shows
  template: show
  dir: galaxie-500/shows
  index_files: true
  name_expr: record['slug'] + "-" + Date.parse(record['date']).strftime('%Y-%m-%d') + record['disambiguate'].to_s + '-' + record['venue-slug']
  title_expr: record['artistname'] + " / " + Date.parse(record['date']).strftime("%-d %B %Y") + " - " + record['venue']
  page_data_prefix: ahfow 
- data: discography.damon-and-naomi-shows
  template: show
  dir: damon-and-naomi/shows
  index_files: true
  name_expr: record['slug'] + "-" + Date.parse(record['date']).strftime('%Y-%m-%d') + record['disambiguate'].to_s + '-' + record['venue-slug']
  title_expr: record['artistname'] + " / " + Date.parse(record['date']).strftime("%-d %B %Y") + " - " + record['venue']
  page_data_prefix: ahfow 


# Build settings
future: true
livereload: false
host: 0.0.0.0
port: 4000
environment: development
markdown: kramdown
kramdown:
    smart_quotes:  ["lsquo", "rsquo", "ldquo", "rdquo"]
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'vendor',
    's3cfg-prog',
    's3cfg-prog.enc',
    'vendor',
    'deploy.sh',
    '_deploy'
  ]
plugins: [
  'jekyll-datapage-generator'
      ]
