# Site settings
title: 'A Head Full of Wishes'
subtitle: 'Releases, shows and tracks'
email: andy@fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://db.fullofwishes.co.uk" # the base hostname and protocol for your site
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
twitter_username: ahfow
github_username:  grange85

collections:
  tracks:
    output: true
    permalink: tracks/:title/
  galaxie-500-releases:
    output: true
    permalink: galaxie-500/releases/:title/
  galaxie-500-shows:
    output: true
    permalink: galaxie-500/shows/:path/
  galaxie-500-articles:
    output: true
    permalink: galaxie-500/articles/:title/
  luna-releases:
    output: true
    permalink: luna/releases/:title/
  luna-shows:
    output: true
    permalink: luna/shows/:path/
  luna-articles:
    output: true
    permalink: luna/articles/:title/
  damon-and-naomi-releases:
    output: true
    permalink: damon-and-naomi/releases/:title/
  damon-and-naomi-shows:
    output: true
    permalink: damon-and-naomi/shows/:path/
  dean-and-britta-releases:
    output: true
    permalink: dean-and-britta/releases/:title/
  dean-and-britta-shows:
    output: true
    permalink: dean-and-britta/shows/:path/
  dean-wareham-releases:
    output: true
    permalink: dean-wareham/releases/:title/
  dean-wareham-shows:
    output: true
    permalink: dean-wareham/shows/:path/
  britta-phillips-releases:
    output: true
    permalink: britta-phillips/releases/:title/
  britta-phillips-shows:
    output: true
    permalink: britta-phillips/shows/:path/


defaults:
  -
    scope:
      path: ""
      type: galaxie-500-shows
    values:
      artistslug: galaxie-500
  -
    scope:
      path: ""
      type: luna-shows
    values:
      artistslug: luna
      date-added: 1994-01-01
  -
    scope:
      path: ""
      type: damon-and-naomi-shows
    values:
      artistslug: damon-and-naomi
      date-added: 1994-01-01
  -
    scope:
      path: ""
      type: dean-and-britta-shows
    values:
      artistslug: dean-and-britta
      date-added: 1994-01-01
  -
    scope:
      path: ""
      type: dean-wareham-shows
    values:
      artistslug: dean-wareham
      date-added: 1994-01-01
  -
    scope:
      path: ""
      type: britta-phillips-shows
    values:
      artistslug: britta-phillips
      date-added: 1994-01-01

# Build settings
port: 4000
environment: production
version: 5.0.0
markdown: kramdown
kramdown:
    smart_quotes:  ["lsquo", "rsquo", "ldquo", "rdquo"]
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    'vendor',
    's3cfg-prog',
    's3cfg-prog.enc',
  ]
plugins: [
        bootstrap-sass
      ]
